<?php

/**
 * @file
 * Token Browser Module
 */

/**
 * Implements hook_library().
 */
function token_browser_library() {
  $libraries['velocity'] = array(
    'title' => 'Velocity.js',
    'version' => '2.0.5',
    'js' => array(
      drupal_get_path('module', 'token_browser') . '/dist/velocity.min.js' => array(),
    ),
  );

  $libraries['token-browser'] = array(
    'title' => 'Token Browser',
    'css' => array(
      drupal_get_path('module', 'token_browser') . '/css/token-browser.css' => array(),
    ),
    'js' => array(
      drupal_get_path('module', 'token_browser') . '/dist/token-browser.js' => array(),
    ),
    'dependencies' => array(
      array('token_browser', 'velocity'),
      array('system', 'ui.dialog'),
    ),
  );

  return $libraries;
}

/**
 * Implements hook_menu().
 */
function token_browser_menu() {
  // Test page with a test form on it.
  $items['token/browser/test'] = array(
    'title' => 'Token Browser Test Page',
    'page callback' => 'token_browser_page',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'includes/token_browser.callback.inc',
  );

  // AJAX endpoint for the assembled tree.
  $items['token/browser/tree'] = array(
    'page callback' => 'token_browser_tree',
    'delivery callback' => 'token_browser_tree_output',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'includes/token_browser.callback.inc',
    'theme callback' => 'ajax_base_page_theme',
  );

  // AJAX endpoint for retrieving a token.
  $items['token/browser/token'] = array(
    'page callback' => 'token_browser_endpoint',
    'delivery callback' => 'drupal_json_output',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'includes/token_browser.callback.inc',
  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function token_browser_theme() {
  $themes['token_browser_link'] = array(
    'variables' => array(
      'text' => 'Browse available tokens.',
    ),
    'file' => 'includes/token_browser.theme.inc',
  );

  return $themes;
}
